version: "3.7"

services:

    sfu:
        image: xtechsample/ion-sfu:latest-allrpc
        command: ["-c", "/configs/sfu.toml", "-jaddr", ":7001" , "-gaddr" , ":50051" , "-eaddr", "176.9.137.77:2379"]
        volumes:
            - "./cfgs/sfu-gcp.toml:/configs/sfu.toml"
        network_mode: host
        restart: always
        # ports:
        #     - "10000-11000:10000-11000/udp"
        #     - 7001:7001

    