version: "3.7"

services:
    etcd:
        image: gcr.io/etcd-development/etcd:v3.4.9
        entrypoint: "/usr/local/bin/etcd"
        command: "--listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379"
        network_mode: host
        # ports:
        #     - 2379:2379

    server:
        image: xtechsample/server
        container_name: server
        build:
            context : ./sfu-coordinator
        image: xtechsample/server-ion:latest
        restart: always
        network_mode: host
        depends_on:
            - etcd

    actions:
        image: xtechsample/actions
        container_name: actions
        build:
            context : actions
        command: ["-port", ":3050", "-ipaddr" , "5.9.18.28" , "-eaddr", "5.9.18.28:2379", "-saddr","5.9.18.28:4000"]
        restart: always
        network_mode: host

    
    sfu:
        image: xtechsample/ion-sfu:latest-allrpc
        build: 
            context: ./ion-sfu
            dockerfile: cmd/signal/allrpc/Dockerfile
        command: ["-c", "/configs/sfu.toml", "-jaddr", ":7002", "-gaddr" , ":50052", "-eaddr", "0.0.0.0:2379", "-ipaddr", "5.9.18.28"]
        volumes:
            - "./cfgs/sfuA.toml:/configs/sfu.toml"
        network_mode: host
        # ports:
        #     - "10000-11000:10000-11000/udp"
        #     - 7001:7001
            

    # sfuB:
    #     image: xtechsample/ion-sfu:latest-allrpc
    #     build: 
    #         context: ./ion-sfu
    #         dockerfile: cmd/signal/allrpc/Dockerfile
    #     command: ["-c", "/configs/sfu.toml", "-jaddr", ":7003", "-gaddr" , ":50053", "-eaddr", "0.0.0.0:2379", "-ipaddr", "5.9.18.28", "-maddr", ":8102"]
    #     volumes:
    #         - "./cfgs/sfuB.toml:/configs/sfu.toml"
    #     network_mode: host

    # sfuB-1:
    #     image: xtechsample/ion-sfu:latest-allrpc
    #     build: 
    #         context: ./ion-sfu
    #         dockerfile: cmd/signal/allrpc/Dockerfile
    #     command: ["-c", "/configs/sfu.toml", "-jaddr", ":7004", "-gaddr" , ":50054", "-eaddr", "0.0.0.0:2379", "-ipaddr", "5.9.18.28", "-maddr", ":8103"]
    #     volumes:
    #         - "./cfgs/sfuB.toml:/configs/sfu.toml"
    #     network_mode: host

    # sfuB-2:
    #     image: xtechsample/ion-sfu:latest-allrpc
    #     build: 
    #         context: ./ion-sfu
    #         dockerfile: cmd/signal/allrpc/Dockerfile
    #     command: ["-c", "/configs/sfu.toml", "-jaddr", ":7005", "-gaddr" , ":50055", "-eaddr", "0.0.0.0:2379", "-ipaddr", "5.9.18.28", "-maddr", ":8104"]
    #     volumes:
    #         - "./cfgs/sfuB.toml:/configs/sfu.toml"
    #     network_mode: host

    # sfuB-3:
    #     image: xtechsample/ion-sfu:latest-allrpc
    #     build: 
    #         context: ./ion-sfu
    #         dockerfile: cmd/signal/allrpc/Dockerfile
    #     command: ["-c", "/configs/sfu.toml", "-jaddr", ":7006", "-gaddr" , ":50056", "-eaddr", "0.0.0.0:2379", "-ipaddr", "5.9.18.28", "-maddr", ":8105"]
    #     volumes:
    #         - "./cfgs/sfuB.toml:/configs/sfu.toml"
    #     network_mode: host

    # sfuB-4:
    #     image: xtechsample/ion-sfu:latest-allrpc
    #     build: 
    #         context: ./ion-sfu
    #         dockerfile: cmd/signal/allrpc/Dockerfile
    #     command: ["-c", "/configs/sfu.toml", "-jaddr", ":7007", "-gaddr" , ":50057", "-eaddr", "0.0.0.0:2379", "-ipaddr", "5.9.18.28", "-maddr", ":8106"]
    #     volumes:
    #         - "./cfgs/sfuB.toml:/configs/sfu.toml"
    #     network_mode: host

    # sfuB-5:
    #     image: xtechsample/ion-sfu:latest-allrpc
    #     build: 
    #         context: ./ion-sfu
    #         dockerfile: cmd/signal/allrpc/Dockerfile
    #     command: ["-c", "/configs/sfu.toml", "-jaddr", ":7008", "-gaddr" , ":50058", "-eaddr", "0.0.0.0:2379", "-ipaddr", "5.9.18.28", "-maddr", ":8107"]
    #     volumes:
    #         - "./cfgs/sfuB.toml:/configs/sfu.toml"
    #     network_mode: host
    
    # sfuB-6:
    #     image: xtechsample/ion-sfu:latest-allrpc
    #     build: 
    #         context: ./ion-sfu
    #         dockerfile: cmd/signal/allrpc/Dockerfile
    #     command: ["-c", "/configs/sfu.toml", "-jaddr", ":7009", "-gaddr" , ":50059", "-eaddr", "0.0.0.0:2379", "-ipaddr", "5.9.18.28", "-maddr", ":8108"]
    #     volumes:
    #         - "./cfgs/sfuB.toml:/configs/sfu.toml"
    #     network_mode: host

    # caddy:
    #     image: caddy:2.3.0-alpine
    #     restart: unless-stopped
    #     ports:
    #         - "85:80"
    #         - "445:443"
    #     volumes:
    #         - ./caddy/Caddyfile:/etc/caddy/Caddyfile