version: "3.7"

services:

    actions:
        image: xtechsample/actions
        container_name: actions
        command: ["server","--port", ":3050" ,"--ipaddr" , "{ip}" , "--eaddr", "176.9.137.77:2379", "--saddr","https://sfu-coordinator.platoo.in/"]
        restart: always
        network_mode: host

    rtmp:
        image: gwuhaolin/livego
        command : "--config_file /etc/livego.yaml"
        volumes:
            - ./cfgs/rtmp/livego.yaml:/etc/livego.yaml
        network_mode: host