version: "3.7"

services:
    etcd:
        image: gcr.io/etcd-development/etcd:v3.4.9
        entrypoint: "/usr/local/bin/etcd"
        command: "--listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379"
        network_mode: host
        # ports:
        #     - 2379:2379

    # server:
    #     container_name: server
    #     build:
    #         context : ./server
    #     image: xtechsample/server-ion:latest
    #     restart: always
    #     environment:
    #         - ETCD=http://0.0.0.0:2379
    #     network_mode: host
    #     depends_on:
    #         - etcd

    

    prometheus:
        image: prom/prometheus:latest
        # ports:
        #     - 9090:9090
        network_mode: host
        volumes:
            - "./cfgs/prometheus.yml:/etc/prometheus/prometheus.yml"

    
    sfu:
        image: xtechsample/ion-sfu:latest-allrpc
        build: 
            context: ./ion-sfu
            dockerfile: cmd/signal/allrpc/Dockerfile
        command: ["-c", "/configs/sfu.toml", "-jaddr", ":7002", "-gaddr" , ":50052", "-eaddr", "0.0.0.0:2379", "-ipaddr", "5.9.18.28", "-maddr", ":8100"]
        volumes:
            - "./cfgs/sfuA.toml:/configs/sfu.toml"
        network_mode: host
        # ports:
        #     - "10000-11000:10000-11000/udp"
        #     - 7001:7001
            

    sfuB:
        image: xtechsample/ion-sfu:latest-allrpc
        build: 
            context: ./ion-sfu
            dockerfile: cmd/signal/allrpc/Dockerfile
        command: ["-c", "/configs/sfu.toml", "-jaddr", ":7003", "-gaddr" , ":50053", "-eaddr", "0.0.0.0:2379", "-ipaddr", "5.9.18.28", "-maddr", ":8102"]
        volumes:
            - "./cfgs/sfuB.toml:/configs/sfu.toml"
        network_mode: host
        # ports:
        #     - "14000-15000:14000-15000/udp"
    

    # caddy:
    #     image: caddy:2.3.0-alpine
    #     restart: unless-stopped
    #     ports:
    #         - "85:80"
    #         - "445:443"
    #     volumes:
    #         - ./caddy/Caddyfile:/etc/caddy/Caddyfile